### ISSUE TITLE
Add some agent/multi-agent demos

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tidb-vector-python#38]
In https://github.com/pingcap/tidb-vector-python/tree/main/examples

**Comment by AntiKnot** [comment]
Using vector-store is one way to implement a retriever, but it is not an essential core function of dspy or llamachain. The example serves only as a demo to show that TiDBVectorClient can be compatible with these features, tools.

If repo need more targeted function, or if it doesn't meet the expectations, any suggestions are welcome.

**Comment by sykp241095** [comment]
Got that, it make sense that "TiDBVectorClient can be compatible with these features, tools".
