### ISSUE TITLE
Refactor __del__ Method to Properly Dispose of SQLAlchemy Engine in TiDBVectorClient

### ISSUE THREAD

**Issue by AntiKnot** [pingcap/tidb-vector-python#51]
### Description
**Description**: The current implementation of the `__del__` method in the TiDBVectorClient class attempts to close a connection by checking if self._bind is an instance of sqlalchemy.engine.Connection. However, self._bind is actually an instance of sqlalchemy.engine.Engine, which means the condition will always evaluate to False, and the engine will not be properly disposed of when the object is deleted.  

**Expected Behavior**: The `__del__` method should ensure that the SQLAlchemy engine (self._bind) is properly disposed of to release the connection pool and resources associated with it.  

**Current Behavior**: The `__del__` method's condition to check if self._bind is an instance of sqlalchemy.engine.Connection is never true because self._bind is an instance of sqlalchemy.engine.Engine. As a result, the engine is not disposed of.

### Code Ref
https://github.com/pingcap/tidb-vector-python/blob/0e95b1209218e23891ed33ca2c29d5b40844438a/tidb_vector/integrations/vector_client.py#L169-L171

https://github.com/pingcap/tidb-vector-python/blob/0e95b1209218e23891ed33ca2c29d5b40844438a/tidb_vector/integrations/vector_client.py#L173-L176

**Comment by arsentievalex** [comment]
Related to this, I'm having an AttributeError when trying to query an index:

Exception ignored in: <function TiDBVectorClient.__del__ at 0x1712a0360>
Traceback (most recent call last):
  File "/Users/username/PycharmProjects/pythonProject/.venv/lib/python3.12/site-packages/tidb_vector/integrations/vector_client.py", line 175, in __del__
AttributeError: 'NoneType' object has no attribute 'Connection'

**Comment by Icemap** [comment]
Hi guys, I fixed these two issues in this PR: https://github.com/pingcap/tidb-vector-python/pull/57 . You can use the fixed version, which is `0.0.11`. So I will close this issue ticket later. If you have any questions, please feel free to reopen it or create a new one. Thanks for your reporting!
